name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - feat
      - feature
      - enhancement
  - title: "🐛 Fixes"
    labels:
      - fix
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore
      - dependencies
      - ci
      - build
  - title: "🧪 Tests"
    labels:
      - test
  - title: "⚙️ Refactors"
    labels:
      - refactor
  - title: "📚 Docs"
    labels:
      - docs
  - title: "⚡ Performance"
    labels:
      - perf

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - major
      - breaking change
      - breaking
  minor:
    labels:
      - feat
      - feature
      - enhancement
  patch:
    labels:
      - fix
      - bug
      - chore
      - docs
      - refactor
      - perf
      - test
      - ci
      - build
      - dependencies
  default: patch

exclude-labels:
  - skip-changelog

prerelease: false
