name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels: ["feat", "feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["fix", "bug"]
  - title: "🧰 Maintenance"
    labels: ["chore", "dependencies", "ci", "build"]
  - title: "🧪 Tests"
    labels: ["test"]
  - title: "⚙️ Refactors"
    labels: ["refactor"]
  - title: "📚 Docs"
    labels: ["docs"]
  - title: "⚡ Performance"
    labels: ["perf"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

version-resolver:
  major:
    labels: ["major", "breaking change", "breaking"]
  minor:
    labels: ["feat", "feature", "enhancement"]
  patch:
    labels: ["fix", "bug", "chore", "docs", "refactor", "perf", "test", "ci", "build", "dependencies"]
  default: patch

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "feat"
    branch:
      - "/^feat[\/-].+/"
    title:
      - "/^feat(\(.+\))?:/i"
  - label: "fix"
    branch:
      - "/^fix[\/-].+/"
    title:
      - "/^fix(\(.+\))?:/i"
  - label: "chore"
    branch:
      - "/^chore[\/-].+/"
    title:
      - "/^chore(\(.+\))?:/i"
  - label: "docs"
    branch:
      - "/^docs[\/-].+/"
    title:
      - "/^docs(\(.+\))?:/i"
  - label: "refactor"
    branch:
      - "/^refactor[\/-].+/"
    title:
      - "/^refactor(\(.+\))?:/i"
  - label: "test"
    branch:
      - "/^test[\/-].+/"
    title:
      - "/^test(\(.+\))?:/i"
  - label: "perf"
    branch:
      - "/^perf[\/-].+/"
    title:
      - "/^perf(\(.+\))?:/i"
  - label: "ci"
    branch:
      - "/^ci[\/-].+/"
    title:
      - "/^ci(\(.+\))?:/i"

prerelease: false
