version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: performance_db
      POSTGRES_USER: perf_user
      POSTGRES_PASSWORD: "Perf_1234!"
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perf_user -d performance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:



