spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/performance_db
    username: perf_user
    password: perf_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
