spring:
  # (opcionális) Fix felhasználónév; jelszó környezeti változóból jön
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:change-me}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/performance_db}
    username: ${DB_USER:perf_user}
    password: ${DB_PASS:Perf_1234!}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false

# swagger / openapi kikapcsolása prodon
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Actuator szűkítése: csak health és info legyen kiexponálva (URL: /actuator/...)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
      probes.enabled: true   # liveness/readiness al-endpointok
    info:
      enabled: true

# Hibaüzenetek ne szivárogjanak prodon
server:
  port: ${SERVER_PORT:8082}
  error:
    include-message: never
    include-stacktrace: never



