spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/performance_db
    username: perf_user
    password: Perf_1234!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/performance_db
    user: perf_user
    password: Perf_1234!

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true