name: Feature request
description: Suggest an idea or improvement
title: "[feat] <short title>"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: ProblĂ©ma leĂ­rĂˇsa
      description: Milyen problĂ©mĂˇt old meg az Ă¶tlet?
      placeholder: "Amikor ... akkor ..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Javasolt megoldĂˇs
      placeholder: "RĂ¶viden a megoldĂˇs: ..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: AlternatĂ­vĂˇk, amiket fontolgattĂˇl
  - type: textarea
    id: acceptance
    attributes:
      label: ElfogadĂˇsi kritĂ©riumok
      placeholder: |
        - [ ] ...
        - [ ] ...
  - type: textarea
    id: context
    attributes:
      label: TovĂˇbbi kontextus / kĂ©pernyĹ‘kĂ©pek
