-- Make 'id' identity ONLY if there's NO identity AND NO default (SERIAL).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'athlete'
      AND column_name = 'id'
      AND (is_identity = 'YES' OR column_default IS NOT NULL)
  ) THEN
    EXECUTE 'ALTER TABLE public.athlete ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END $$;

-- Safe defaults for timestamps (ok even if already set)
ALTER TABLE public.athlete
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET DEFAULT now();
