name: build

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Wrapper validation ideiglenesen kiiktatva a runner hálózati flake miatt

      - name: Build (no tests for now)
        run: ./gradlew --no-daemon clean build -x test
