name: build

on:
  push:
    branches: [ main, develop, 'feat/**' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Gradle version (warm up)
        run: ./gradlew -Dorg.gradle.java.home=$JAVA_HOME --no-daemon --version

      - name: Build (no tests for now)
        run: ./gradlew -Dorg.gradle.java.home=$JAVA_HOME --no-daemon clean build -x test

