name: build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "main"
      - "ci/**"
      - "feat/**"
      - "fix/**"
      - "chore/**"
      - "docs/**"
      - "repo/**"
      - "refactor/**"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 21 (Temurin) with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build & test (Spring profile: test)
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean build --no-daemon
