name: build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build gyorsan, tesztek nélkül (a tesztek külön workflow-ban futnak)
      - name: Gradle build (no tests)
        run: ./gradlew --no-daemon -x test build
