name: CI - Gradle Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Testcontainers a GitHub Ubuntu runneren alapból működik (Docker elérhető)
      - name: Run tests
        run: ./gradlew --no-daemon test
