name: Tests (manual) + JaCoCo

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Csak infó: Docker elérhető a runneren (Testcontainers ezt fogja használni)
      - name: Docker info
        run: |
          docker --version
          docker info -f 'Server: {{.ServerVersion}}'

      - name: Run tests + JaCoCo (with Testcontainers JDBC)
        env:
          SPRING_PROFILES_ACTIVE: test
          # ezek itt nem feltétlen kellenek, de ártani nem ártanak
          TESTCONTAINERS_CHECKS_DISABLE: 'true'
        run: ./gradlew --no-daemon clean test jacocoTestReport

      - name: Upload JUnit report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test

      - name: Upload JaCoCo (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
