name: Tests (manual) + JaCoCo

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests + JaCoCo (with Testcontainers JDBC)
        # Nem indítunk külön DB-servicet; a Testcontainers JDBC URL indítja a Postgrest
        run: ./gradlew --no-daemon clean test jacocoTestReport
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:tc:postgresql:16:///perf
          # Opcionális (a JDBC driver nem igényli, de Spring felől nem árt):
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres

      - name: Upload JUnit report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test
          if-no-files-found: warn

      - name: Upload JaCoCo (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
          if-no-files-found: warn
