name: Tests (manual) + JaCoCo

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests + JaCoCo
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_JPA_HIBERNATE_DDL_AUTO: validate
          SPRING_FLYWAY_ENABLED: true
        run: |
          ./gradlew --no-daemon \
            -Dspring.profiles.active=test \
            -Dspring.datasource.url=$SPRING_DATASOURCE_URL \
            -Dspring.datasource.username=$SPRING_DATASOURCE_USERNAME \
            -Dspring.datasource.password=$SPRING_DATASOURCE_PASSWORD \
            clean test jacocoTestReport

      - name: Upload JUnit report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test

      - name: Upload JaCoCo (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
